#pragma once

enum IMG{									//Enumeration des differentes images possibles
	DEMARRAGE_NEUTRE,
	DEMARRAGE_JOUER,
	DEMARRAGE_HIGHSCORE,
	DEMARRAGE_QUITTER,
	CORDE_PLUS,
	CORDE_MOINS,
	BOULET_PLUS,
	BOULET_MOINS,
	MOUETTE_PLUS,
	MOUETTE_MOINS,
	CONFIRMER,
	AMELIORATION_AUCUN,
	BACKGROUND,
	TEXTURE_GRAINS
};
